name: Auto Push

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间的午夜执行，您可以根据需要调整时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'RManLuo'
          git config --global user.email 'RManLuo@noreply.com'

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Auto commit $(date +'%Y-%m-%d %H:%M:%S')"
          git push
