name: v2ex

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '8 0 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！

jobs:
  v2ex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Run task
        run: node src/v2ex.js
        env:
          V2EX_A2: ${{ secrets.V2EX_A2 }}

