name: v2ex

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '9 0 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天8点8分
    # 注意V站领取奖励刷新时间为每天8点后，所以时间不要设置在8点之前
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量V站同一个IP在相同时间去请求B站接口，导致IP被禁！

jobs:
  v2ex:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn
        
      - name: Build Source
        run: yarn build
        
      - name: Run task
        run: yarn v2ex
        env:
          V2EX_A2: ${{ secrets.V2EX_A2 }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
